"""Build the reproducible demo capture, demo/demo.pcap (docs: README "Watch it work", DEPLOY.md).

11 minutes of capture time:
- Background: every packet to or from the hand-checked normal hosts of CTU-13-Extended scenario 5
  (header-only, real traffic) during the capture's first 11 minutes, re-timed to start at T0.
  The original wire length of each packet is kept in the record header.
- Attacks, all generated by sih26145.utils.attack_scenarios, on a quiet link first:
    0:00-2:00  background only
    2:00       port scan from host H                            (e) recon
    2:30-7:15  C2 check-ins from H every ~15 s                  (b) C2
    5:00-5:50  rare-JA4 TLS sessions from H to another server   (d) encrypted
    7:00       DGA lookups from H                               (c) DGA
    8:00       DNS tunnel from H                                (c) tunnel
    9:20       1.2 MB upload from H                             (f) exfiltration
    10:00      SYN flood on a different internal server         (a) DDoS
  H = 192.168.1.66: every H stage is one campaign; the flood is another.

Run with SIH26145_INTERNAL_CIDRS=147.32.0.0/16,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12 so the
university hosts and the generated enclave are both "internal".

    uv run python scripts/build_demo_capture.py [--out demo/demo.pcap]
"""

import argparse
import csv
import hashlib
import socket
import struct
from pathlib import Path

import dpkt

from sih26145.ingest.reader import capture_records
from sih26145.utils import attack_scenarios as atk
from sih26145.utils.benign_scenarios import T0

DATA = Path.home() / "NewProjects/26145-data"
SOURCE = DATA / "ctu13-extended/capture20110815-2.truncated.pcap"   # CTU-13-Extended scenario 5
LABELS = DATA / "extracted/CTU-13-Dataset/5/capture20110815-2.binetflow"
SPAN_S = 660.0
HOST = "192.168.1.66"
INTERNAL_CIDRS = "147.32.0.0/16,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12"


def normal_hosts() -> set:
    with open(LABELS, newline="") as fh:
        return {r["SrcAddr"] for r in csv.DictReader(fh) if r["Label"].startswith("flow=From-Normal")}


def background():
    """(t, frame, wire_len) of the normal hosts' packets in the first SPAN_S seconds, re-timed."""
    keep = {socket.inet_aton(ip) for ip in normal_hosts()}
    out, start = [], None
    with open(SOURCE, "rb") as f:
        for ts, buf, wirelen in capture_records(f):
            start = ts if start is None else start
            if ts - start >= SPAN_S:
                break
            try:
                ip = dpkt.ethernet.Ethernet(buf).data
            except (dpkt.UnpackError, IndexError):
                continue
            if isinstance(ip, dpkt.ip.IP) and (ip.src in keep or ip.dst in keep):
                out.append((T0 + (ts - start), buf, wirelen))
    return out


def attacks():
    """(t, frame, wire_len): generated packets are whole, so wire length = frame length."""

    def h(pkts, src):
        return atk.readdress(pkts, {src: HOST})

    pkts = (h(atk.port_sweep(T0 + 120), "192.168.1.52")
            + h(atk.c2_beacon(T0 + 150, period=15.0), "192.168.1.70")
            + h(atk.tls_beacon(T0 + 300), "192.168.1.90")
            + h(atk.dga_lookups(T0 + 420), "192.168.1.80")
            + h(atk.dns_tunnel(T0 + 480), "192.168.1.81")
            + h(atk.exfil_upload(T0 + 560), "192.168.1.51")
            + atk.syn_flood(T0 + 600))
    return [(t, buf, len(buf)) for t, buf in pkts]


def write_pcap(path: Path, records) -> None:
    """Classic pcap, microsecond, Ethernet; each record keeps its original wire length."""
    with open(path, "wb") as f:
        f.write(struct.pack("<IHHiIII", 0xA1B2C3D4, 2, 4, 0, 0, 65535, 1))
        for t, buf, wirelen in sorted(records, key=lambda r: r[0]):
            sec, usec = divmod(int(round(t * 1e6)), 1_000_000)
            f.write(struct.pack("<IIII", sec, usec, len(buf), wirelen))
            f.write(buf)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="demo/demo.pcap")
    out = Path(ap.parse_args().out)
    out.parent.mkdir(parents=True, exist_ok=True)
    bg, at = background(), attacks()
    write_pcap(out, bg + at)
    digest = hashlib.sha256(out.read_bytes()).hexdigest()
    print(f"{out}: {len(bg)} background + {len(at)} generated packets, {out.stat().st_size / 1e6:.1f} MB, "
          f"span {SPAN_S:.0f} s\nsha256 {digest}")


if __name__ == "__main__":
    main()
